
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: french
    description: "test french table"
    columns:
      - name: FR
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: french
    description: "test french table"
    columns:
      - name: FR
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - accepted_values:
              values:  ['un', 'deux']

  - name: enfr
    description: "EN-FR mapping"
    columns:
      - name: fr
        tests:
          - accepted_values:
              values: ['un', 'deux', 'trois']

  - name: ende
    description: "EN-DE mapping"
    columns:
      - name: de
        tests:
          - accepted_values:
              values: ['einz', 'zwei', 'drei']

  - name: enfr
    description: "Ensure EN matches EN in ende"
    columns:
      - name: en
        tests:
          - relationships:
              to: ref('ende')
              field: en
